[package]
name = "strafe-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-executor = "1.5.1"
bytemuck = { version = "1.13.1", features = ["derive"] }
ddsfile = "0.5.1"
env_logger = "0.10.0"
glam = "0.24.1"
log = "0.4.20"
obj = "0.10.2"
pollster = "0.3.0"
wgpu = "0.17.0"
winit = "0.28.6"

# https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies

[target.wasm32-unknown-unknown.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
js-sys = "0.3.64"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.64", features = ["Location", "Window"] }
